"""remove_album_photos_model

Revision ID: 9476a9125aef
Revises: a7215ff16d96
Create Date: 2021-06-07 01:40:12.451091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9476a9125aef'
down_revision = 'a7215ff16d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albumphotos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albumphotos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name='albumphotos_album_id_fkey'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name='albumphotos_photo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='albumphotos_pkey')
    )
    # ### end Alembic commands ###
